[package]
name = "custom_msgs"
version = "0.0.0"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }
builtin_interfaces = "*"
geometry_msgs = "*"
std_msgs = "*"

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde', 'builtin_interfaces/serde', 'geometry_msgs/serde', 'std_msgs/serde']
